### ISSUE TITLE
Implement player's party

### ISSUE THREAD

**Issue by xuganyu96** [xuganyu96/untitled-badminton-app#16]
The specification is listed in [here](https://xuganyu96.github.io/untitled-badminton-app/02-players-party)

# To-do's
First some clean-ups
- [x] Write unit tests for `backend.users` methods

Then the real stuff
- [x] add `users.root_id` column and relationship for `user.root`
- [x] add `users.invite_code` column
- [x] Implement `/play/party` route
- [x] Implement `/play/party/join` route
- [x] Implement `/play/party/manage` route
- [x] Implement `/play/party/remove` route
- [x] Implement `/play/party/leave` route
- [x] Add quick action card to `/play/home`

**Comment by xuganyu96** [comment]
By default all non-root members will be allowed to invite. If the root user wants to revoke invite just remove the non-root member.
