### ISSUE TITLE
Implement gyms and courts data models and routes

### ISSUE THREAD

**Issue by xuganyu96** [xuganyu96/untitled-badminton-app#19]
[spec](https://xuganyu96.github.io/untitled-badminton-app/03-gyms-and-courts)

# To-do's
- [x] Implement `Gym` and `Court` model
- [x] Implement `/play/search` route
- [x] Implement `/play/gyms/<gym_id>` route
