### ISSUE TITLE
Ticketing system

### ISSUE THREAD

**Issue by xuganyu96** [xuganyu96/untitled-badminton-app#21]
[spec](https://xuganyu96.github.io/untitled-badminton-app/04-ticketing)

# To-do's
- [x] Implement `Ticket` data model
- [x] Implement `heartbeat_court`
- [x] Implement `/play/gyms/<gym_id>/confirm`
- [x] Implement `/play/locked`
- [x] Implement `autolock` decorator
- [x] Implement `/play/cancel`
- [x] Implement scheduler

**Comment by xuganyu96** [comment]
# test scenario
`leader0` drops in alongside `follower0a`, `follower0b`, and `follower0c`. All of them should be immediately activated.

Then `leader1` drops in alongside `follower1a`, `follower1b`, `follower1c`. Their lock should show that they are next in line.

Then sign in as each member of party 0 and cancel the ticket. When the last member is canceled, the heartbeat should detect capacity and bring party 1 to "active".
