### ISSUE TITLE
Challenger court workflow

### ISSUE THREAD

**Issue by xuganyu96** [xuganyu96/untitled-badminton-app#26]
[spec](https://xuganyu96.github.io/untitled-badminton-app/06-challenger-court)

# To-do's
- [x] Define the `court_hours` table
- [x] Add "upcoming court hours" in the gym view
- [x] Add "number of open courts" in the gym quick view card
- [x] Refactor drop-in such that outside drop-in hours, the confirmation page cannot be used to request ticket.
- [x] Change "court rental" to "challenge"
- [x] Change `confirm` to `confirm_dropin` and build `confirm_challenge`
- [ ] The challenge workflow:

Some miscellaneous features:
- [ ] the open hours in gym view can be color coded depending on single/double/dropin

**Comment by xuganyu96** [comment]
# Data model for challenge tickets
A challenger's ticket still exists in the `tickets` table, but the challenge workflow is a bit different from the drop-in tickets:

1. challenger tickets are distinct from drop-in tickets, so a flag `is_challenge` should distinguish the two kinds of tickets
2. challenger ticket's `activated_ts` is the time at which the player is "called onto court," which is distinct from the time at which the player starts the game. More details below.
3. challenger's presence needs to be acknowledged by the opponent, so there needs to a timestamp that indicates the time at which the ticket holder's presence is acknowledged: `presented_ts`
4. challenger's absence is detected by the scheduler, so there needs to be another timestamp for when the ticket was timed out: `noshow_ts`
5. the winner's ticket is also expired, but the winner will be immediately issued a new ticket with the same `created_ts` as the original ticket. This creates a chain of "consecutive wins," which can be more easily captured with a `predecessor_id` and `generation`, which respectively indicates which ticket is the winner before the current one, and the number of consecutive wins that exists prior to the current ticket

**Comment by xuganyu96** [comment]
# Drop-in session length and challenge timeout
Both `Court.session_len` and the challenge timeout should be configurable on a `CourtHour` basis, but they should not be manually entered all the times.

Instead:
- [ ] Set a `default_session_len` and `default_challenge_timeout` (both in minutes) on a per-gym level
- [ ] When a `CourtHour` is first inserted, use the default; later on with Admin views it should be configurable

**Comment by xuganyu96** [comment]
# The "no-show" process:
It does not make sense that the players acknowledge each other's presence. If a player is present, but the other player is not, then even the present player's presence cannot be acknowledged, and the present player will also be timed out.

So for now, presence will be automatically acknowledged, but later on with TOTP, a player's presence will be acknowledged with a TOTP.

**Comment by xuganyu96** [comment]
# There are a lot more edge cases
How to declare winner in challenger
What happens if one party leaves half way
What if one party leaves but doesn't cancel?

**Comment by xuganyu96** [comment]
# on-pause
Challenger's court is a far more complicated problem than I initially expected, and it is probably not a worthy proposition. Let's focus on the drop-in functions first.
